query Pages($slug: String!) {
    Pages(slug: $slug) {
        title
        slides(filter: {isPublished: true})
        {
         title
         description
         imageUrl
        }
        blogs{
         title
         excerpt
         slug
         categories
        }
        alumnis
        {
          title
          name
          airline
          imageUrl
        }
    }
}